apiVersion: v1
kind: ConfigMap
metadata:
  name: asset-management-config
  namespace: asset-management
data:
  DJANGO_SETTINGS_MODULE: "asset_management.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,*.amazonaws.com"
  CORS_ALLOWED_ORIGINS: "https://your-frontend-domain.com"
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True" 